# Generated by Django 3.2 on 2021-04-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoProduit',
            fields=[
                ('tigID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(default='-1', max_length=255)),
                ('category', models.IntegerField(default='-1')),
                ('price', models.FloatField(default='-1.0')),
                ('unit', models.TextField(default='-1', max_length=255)),
                ('availability', models.BooleanField(default=False)),
                ('sale', models.BooleanField(default=False)),
                ('discount', models.FloatField(default='-1.0')),
                ('comments', models.TextField(default='-1', max_length=255)),
                ('owner', models.TextField(default='-1', max_length=255)),
                ('quantity_stock', models.IntegerField(default='-1')),
                ('quantity_sold', models.IntegerField(default='-1')),
                ('price_on_sale', models.FloatField(default='-1.0')),
            ],
            options={
                'ordering': ('tigID',),
            },
        ),
    ]
